# Artificial Neural Network

### Importing the libraries

In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [2]:
tf.__version__ #print da versao do tensorflow do google colab

'2.19.0'

## Part 1 - Data Preprocessing

### Importing the dataset

In [3]:
dataset = pd.read_csv('Churn_Modelling.csv')
X = dataset.iloc[:, 3:-1].values #queremos tirar as duas primeiras colunas porque sao irrelevantes (número de customer e afins). Vai da 4 coluna ate à penúltima
y = dataset.iloc[:, -1].values #variavel dependente

In [4]:
print(X)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]


In [5]:
print(y)

[1 0 1 ... 1 1 0]


### Encoding categorical data

Label Encoding the "Gender" column

In [6]:
#trabalhar a coluna gender para ficar encoded.
from sklearn.preprocessing import LabelEncoder #encoder
le = LabelEncoder() #object. Não precisamos de dar inputs porque é só uma coluna
X[:, 2] = le.fit_transform(X[:, 2])

In [7]:
print(X)

[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]


One Hot Encoding the "Geography" column

In [8]:
#fazer o mesmo para a geography, só que One Hot Encoding

#Olhando para cima, ficou na coluna 1 -> basta alterar para a coluna 1
from sklearn.compose import ColumnTransformer #transformar colunas
from sklearn.preprocessing import OneHotEncoder #para a tecnica one hot encoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [9]:
print(X)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


### Splitting the dataset into the Training set and Test set

In [10]:
from sklearn.model_selection import train_test_split #funcao para split de train e test

X_train, X_test, Y_train, Y_test = train_test_split(X, y, test_size = 0.2, random_state = 1)

### Feature Scaling

In [11]:
#OBRIGATORIO EM ANN. APLICAR EM TUUUDO
from sklearn.preprocessing import StandardScaler
sc = StandardScaler() #object do standard scaler
X_train = sc.fit_transform(X_train) #aplicar em tudo
X_test = sc.fit_transform(X_test) #aplicar em tudo

## Part 2 - Building the ANN

### Initializing the ANN

In [12]:
#tensor flow
ann = tf.keras.models.Sequential() #object da classe sequential para representar a Artificial Neural Network

### Adding the input layer and the first hidden layer

In [13]:
#INPUT LAYER (first hidden layer)
ann.add(tf.keras.layers.Dense(units=6, activation='relu')) #add layers to ANN
#units -> quantos inputs vao haver? -> Colunas que importam nos dados (INPUTS)
#activation parameter -> rectifier (ReLu)


### Adding the second hidden layer

In [14]:
#SECOND HIDDEN LAYER
ann.add(tf.keras.layers.Dense(units=6, activation='relu')) #igual ao anterior, com funcao de ativacao igual e tudo.

### Adding the output layer

In [15]:
#OUTPUT
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid')) # NOTA IMP - SE FOSSE UMA CLASSIFICACAO NAO BINARIA - SOFTMAX
#muito importante: para decidir units de saida:
#É olhar para asdimensoes do output - binary value (0 ou 1) logo basta 1 neurónio para isso!
#Caso fosse non-binary (EX: A, B, C), em que tivessemos que fazer one hot enconding seria 3 neurónios. (porque seriam arrays de 3 valores)

## Part 3 - Training the ANN

### Compiling the ANN

In [16]:
ann.compile(optimizer = 'adam', loss ='binary_crossentropy', metrics = ['accuracy'])
#optimizer -> adam -> gradient descent: update the weights giving the error
#loss -> tem que ser binary crossentropy porque estamos a ver classificações binaria. Se n fosse --> crossentropy
#metrics -> accuracy

### Training the ANN on the Training set

In [18]:
#TREINAR
ann.fit(X_train, Y_train, batch_size = 32, epochs = 100) #batch size: numero de predictions para comparar com real results. 32 costuma ser o usado
#epochs (numero de geracoes) e esperar aumentar accuracy!

Epoch 1/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 6s 7ms/step - accuracy: 0.5224 - loss: 0.7192
Epoch 2/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.7950 - loss: 0.5044
Epoch 3/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - accuracy: 0.8010 - loss: 0.4473
Epoch 4/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.8113 - loss: 0.4374
Epoch 5/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8175 - loss: 0.4239
Epoch 6/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8228 - loss: 0.4150
Epoch 7/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8271 - loss: 0.4113
Epoch 8/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8243 - loss: 0.4136
Epoch 9/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8217 - loss: 0.4172
Epoch 10/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8346 - loss: 0.3984
Epoch 11/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8273 - loss: 0.4038
Epoch 12/100
250/250 ━━━━━━━━━━━━━━━━━━━━

## Part 4 - Making the predictions and evaluating the model

### Predicting the result of a single observation

**Homework**

Use our ANN model to predict if the customer with the following informations will leave the bank:

Geography: France

Credit Score: 600

Gender: Male

Age: 40 years old

Tenure: 3 years

Balance: \$ 60000

Number of Products: 2

Does this customer have a credit card? Yes

Is this customer an Active Member: Yes

Estimated Salary: \$ 50000

So, should we say goodbye to that customer?

**Solution**

In [23]:
#Como fazer predict?
#tem que se transformar com o feature scaling.

print(ann.predict(sc.transform([[1, 0, 0, 600, 1, 40, 3, 60000, 2, 1, 1, 50000]])) > 0.5) #caso nao queira a probabilidade de ser 1 (ele sair) mas sim ver se ele vai sair ou nao,
#metemos aí o 0.5 como threshold. Se for acima disso, fica 1. Se nao for, fica 0.

#sempre em double pair brackets!

#IMPORTANTE:
#O que meter dentro do sc.transform: Ver a partir de onde se vêem as colunas observacao!
#No nosso caso, primeiro é CREDITSCORE e não GEOGRAPHY. Mas como aplicámos One Hot Encoder, geography ficou primeiro!
#Portanto lê-se primeiro geography e depois os restantes na ordem normal das colunas.
#France -> não colocamos em string. Como fizemos one hot encoding ... temos que ver como fica France
        #Em cima vê-se um customer de França que ficou 1 0 0. Logo France é 1 0 0
#Creditscore 600
#Male -> igual a france, vê-se que é 1
#Age
#Tenure
#Balance
#Number of products
#Credit card -> yes -> 1
#Active member? Yes -> 1
#Salary -> 50000

#Deu false! Logo predicts que ele nao vai sair do banco

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step
[[False]]


Therefore, our ANN model predicts that this customer stays in the bank!

**Important note 1:** Notice that the values of the features were all input in a double pair of square brackets. That's because the "predict" method always expects a 2D array as the format of its inputs. And putting our values into a double pair of square brackets makes the input exactly a 2D array.

**Important note 2:** Notice also that the "France" country was not input as a string in the last column but as "1, 0, 0" in the first three columns. That's because of course the predict method expects the one-hot-encoded values of the state, and as we see in the first row of the matrix of features X, "France" was encoded as "1, 0, 0". And be careful to include these values in the first three columns, because the dummy variables are always created in the first columns.

### Predicting the Test set results

In [24]:
y_pred = ann.predict(X_test) #predict com o classifier treinado
y_pred = (y_pred > 0.5) #retorna true caso > 0.5, false caso contrario. Aplicavel ao nosso caso pois a saída é binária
print(np.concatenate((y_pred.reshape(len(y_pred),1), Y_test.reshape(len(Y_test),1)),1)) #print do que foi predict vs o real

63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step
[[0 0]
 [0 0]
 [0 0]
 ...
 [0 0]
 [0 0]
 [1 0]]


### Making the Confusion Matrix

In [25]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(Y_test, y_pred) #shows correct predictions and incorrect predictions
print(cm) #print da matrix
accuracy_score(Y_test, y_pred) #print da acurácia

#1534 e 195 -> correct da 0 e da 1 respetivamente
# 51 e 220 -> incorrect da 0 e 1 respetivamente
#0.87 -> 87% de corretas

[[1534   51]
 [ 220  195]]


0.8645